apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: petclinic-deploy-dev
spec:
  params:
    - name: APP_SOURCE_GIT
      type: string
      description: The application git repository
      default: https://github.com/sree77hari/ocp-cicd.git
    - name: APP_SOURCE_REVISION
      type: string
      description: The application git revision
      default: main
    - name: APP_CONFIG_GIT
      type: string
      description: The application configuration git repository
      default: https://github.com/sree77hari/gitops.git
    - name: APP_IMAGE
      type: string
      default: image-registry.openshift-image-registry.svc:5000/ci-argocd-dev/myapp
      description: The application image to build
    - name: APP_IMAGE_TAG
      type: string
      default: latest
      description: The application image tag to build
  workspaces:
  - name: workspace
  - name: maven-settings
  tasks:
  - name: source-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: workspace
    params:
    - name: url
      value: $(params.APP_SOURCE_GIT)
    - name: revision
      value: $(params.APP_SOURCE_REVISION)
    - name: depth
      value: "0"
    - name: subdirectory
      value: ocp-cicd
    - name: deleteExisting
      value: "true"
  - name: unit-tests
    taskRef:
      name: maven
    runAfter:
      - source-clone
    workspaces:
    - name: source
      workspace: workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: GOALS
      value: ["package", "-f", "ocp-cicd"]
  - name: code-analysis
    taskRef:
      name: maven
    runAfter:
      - source-clone
    workspaces:
    - name: source
      workspace: workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: GOALS
      value:
      - install
      - sonar:sonar
      - -f
      - ocp-cicd
      - -Dsonar.host.url=http://sonarqube:9000
      - -Dsonar.userHome=/tmp/sonar
      - -DskipTests=true
  - name: dependency-report
    taskRef:
      name: dependency-report
    runAfter:
      - source-clone
    workspaces:
    - name: source
      workspace: workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: SOURCE_DIR
      value: ocp-cicd
  - name: release-app
    taskRef:
      name: maven
    runAfter:
      - code-analysis
      - dependency-report
      - unit-tests
    workspaces:
    - name: source
      workspace: workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: GOALS
      value:
      - deploy
      - -f 
      - ocp-cicd
      - -DskipTests=true
      - -DaltDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-releases/
      - -DaltSnapshotDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-snapshots/
  - name: build-image
    taskRef:
      name: s2i-java-11
    runAfter:
    - release-app
    params:
      - name: TLSVERIFY
        value: "false"
      - name: MAVEN_MIRROR_URL
        value: http://nexus:8081/repository/maven-public/
      - name: PATH_CONTEXT
        value: ocp-cicd/target
      - name: IMAGE_NAME
        value: $(params.APP_IMAGE)
      - name: IMAGE_TAG
        value: $(params.APP_IMAGE_TAG)
    workspaces:
    - name: source
      workspace: workspace
  - name: config-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: workspace
    runAfter:
    - build-image
    params:
    - name: url
      value: $(params.APP_CONFIG_GIT)
    - name: subdirectory
      value: gitops
    - name: deleteExisting
      value: "true"
  - name: deploy-dev
    taskRef:
      name: deploy-app
    runAfter:
      - config-clone
      - tests-clone
    params:
    - name: DEPLOYMENT_NAME
      value: myapp
    - name: CURRENT_IMAGE
      value: "quay.io/srereddy/sample:v1.10"
    - name: NEW_IMAGE_NAME
      value: $(params.APP_IMAGE)
    - name: NEW_IMAGE_TAG
      value: $(params.APP_IMAGE_TAG)
    - name: NEW_IMAGE_DIGEST
      value: $(tasks.build-image.results.IMAGE_DIGEST)
    - name: NAMESPACE
      value: demo-dev
    - name: KUSTOMIZE_OVERLAY_DIR
      value: argo
    workspaces:
    - name: source
      workspace: workspace
      subPath: gitops
